<?php

function pet_menu() {
    $items = array();
    $items['tipper_the_dog'] = array(
            'title' => "Tipper!",
            'page callback' => 'meet_tipper',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    return $items;

}

function meet_tipper() {
    $link = '<img src="sites/all/modules/images/tipper.PNG" width=200px>
    <p>Tippper is a beautiful lady foxhound.</p>
    <a href="https://www.instagram.com/explore/tags/tipperthedog/">Here are more pictures of this beautiful pup!</a>';
    return $link;
}
